# Generated by Django 4.2.6 on 2023-10-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplicationpss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applicationpss_user_key', to='PasswordManager.passwordmodel')),
            ],
        ),
    ]
