# Generated by Django 4.2.6 on 2023-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordModel',
            fields=[
                ('parol', models.CharField(max_length=32)),
                ('user', models.CharField(default='username', max_length=16, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
